name: flutter_liff_maps
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  cloud_functions: ^4.3.2
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  geoflutterfire_plus: ^0.0.12
  google_maps_flutter: ^2.2.8
  google_maps_flutter_web: ^0.5.0
  js: ^0.6.7
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
