name: Deploy to Firebase Hosting and Functions on merge

on:
  push:
    branches:
      - main
jobs:
  deploy_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b 3.3.1 "$GITHUB_WORKSPACE/_flutter"
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Download Flutter packages
        run: flutter pub get

      - run: flutter build web --dart-define-from-file='${{ secret.DART_DEFINE }}'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: flutter-liff-maps
  deploy_funcsions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          git clone