name: Deploy to Firebase Hosting and Functions on merge

on:
  push:
    branches:
      - main
jobs:
  deploy_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b 3.10.2 "$GITHUB_WORKSPACE/_flutter"
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH
      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH
      - name: Download Flutter packages
        run: flutter pub get
      - name: setup web/index.html
        run: |
          sed -e "s/YOUR-API-KEY-HERE/${{ secrets.GOOGLE_MAP_API_KEY }}/g" web/index.html.template > web/index.html
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "dart-define.json"
          json: ${{ secrets.DART_DEFINE }}
          dir: "."
      - run: flutter build web --dart-define-from-file='dart-define.json'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: flutter-liff-maps
  